apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubi-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubi-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubi-user
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubi-deployment
  labels:
    app: kubi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubi
  template:
    metadata:
      labels:
        app: kubi
    spec:
      serviceAccountName: kubi-user
      containers:
        - name: kubi
          image: efortin/kubi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: kubi-tls
              mountPath: "/var/run/secrets/certs"
              readOnly: true
          env:
            - name: APISERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: APISERVER_URL
            - name: LDAP_USERBASE
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: LDAP_USERBASE
            - name: LDAP_GROUPBASE
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: LDAP_GROUPBASE
            - name: LDAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: LDAP_SERVER
            - name: LDAP_PORT
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: LDAP_PORT
            - name: LDAP_BINDDN
              valueFrom:
                configMapKeyRef:
                  name: kubi-config
                  key: LDAP_BINDDN
            - name: LDAP_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kubi-secret
                  key: ldap_passwd
      volumes:
        - name: kubi-tls
          secret:
            secretName: kubi
---

apiVersion: v1
kind: Service
metadata:
  name: kubi-svc
spec:
  type: NodePort
  ports:
    - name: https
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30003
  selector:
    app: kubi
