---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkpolicyconfigs.ca-gip.github.com
spec:
  group: ca-gip.github.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: networkpolicyconfigs
    singular: networkpolicyconfig
    kind: NetworkPolicyConfig
    shortNames:
      - netpolconf
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: projects.ca-gip.github.com
spec:
  group: ca-gip.github.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
      - project